### ISSUE TITLE
Path wrong when using Apollo

### ISSUE THREAD

**Issue by ryaneford** [JMTK/SunshineGameFinder#34]
When I run the client it looks specifically for  `C:\Program Files\Sunshine\config\apps.json`

I am running Apollo which is at `C:\Program Files\Apollo`

Can i fix this or does this need some sort of revision?

**Comment by JMTK** [comment]
> When I run the client it looks specifically for `C:\Program Files\Sunshine\config\apps.json`
> 
> I am running Apollo which is at `C:\Program Files\Apollo`
> 
> Can i fix this or does this need some sort of revision?

Very interesting! I'm not familiar with this tool. It does appear to follow the same apps.json structure as Sunshine!

If so, you should be able to override the default location like so:
```bash
SunshineGameFinder.exe --sunshineConfigLocation "C:\Program Files\Apollo\someconfiglocation.json"
```

**Comment by ryaneford** [comment]
> > When I run the client it looks specifically for `C:\Program Files\Sunshine\config\apps.json`
> > I am running Apollo which is at `C:\Program Files\Apollo`
> > Can i fix this or does this need some sort of revision?
> 
> Very interesting! I'm not familiar with this tool. It does appear to follow the same apps.json structure as Sunshine!
> 
> If so, you should be able to override the default location like so:
> 
> ```shell
> SunshineGameFinder.exe --sunshineConfigLocation "C:\Program Files\Apollo\someconfiglocation.json"
> ```

Amazing! 

Some feedback: Can you add a section in your readme for launch variables etc?  Or maybe even breaking out the variables to a config file we can edit?

I look forward to using this tool.  Thanks for all you do!

**Comment by ryaneford** [comment]
Just an update: I ran it with these arguments and it worked.

**Comment by JMTK** [comment]
> > > When I run the client it looks specifically for `C:\Program Files\Sunshine\config\apps.json`
> > > I am running Apollo which is at `C:\Program Files\Apollo`
> > > Can i fix this or does this need some sort of revision?
> > 
> > 
> > Very interesting! I'm not familiar with this tool. It does appear to follow the same apps.json structure as Sunshine!
> > If so, you should be able to override the default location like so:
> > ```shell
> > SunshineGameFinder.exe --sunshineConfigLocation "C:\Program Files\Apollo\someconfiglocation.json"
> > ```
> 
> Amazing!
> 
> Some feedback: Can you add a section in your readme for launch variables etc? Or maybe even breaking out the variables to a config file we can edit?
> 
> I look forward to using this tool. Thanks for all you do!

Glad it worked out! I have added the command line arguments here in the README https://github.com/JMTK/SunshineGameFinder/blob/main/README.md#command-line-arguments
